### ISSUE TITLE
Hdiff Pack isnt working

### ISSUE THREAD

**Issue by DanDanTheDanDan** [alexpado/hoyoverse-music-unpacker#13]
i dont really know what the problem is i put it inside the Genshin Impact folder i get this issue 
-- Detected Genshin Impact !
No update package found.
PS D:\Games\hoyoverse-music-unpacker>
and tried even the zip version of the Hdiff folder

**Comment by alexpado** [comment]
Hi,

Unless I'm totally behind schedule, there is still no update package available through the launcher yet. 

The next update package should be available from the 14th of August to the 16th of August.

Until then, run the extraction without the `--diff` option.

Hope it helps
